server:
  port: 8080

spring:
  application:
    name: scrum-poker


logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

  file: log/${spring.application.name}.log